baseURL = 'https://thankful-coast-0276afe10.2.azurestaticapps.net'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'learn'
themesdir = "../themes"

[params]
  editURL = "https://github.com/dlturner21/hugo-static-app/edit/main/TestDocSite/content/"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  ## titleSeparator = "::"